# Site settings
title: Ionic Training
description: A blog about lorem ipsum dolor sit amet

# User settings
username: Lorem Ipsum
user_description: Ionic Training at Lorem Ipsum Dolor
email: anon@anon.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
